Pretty-print binary blobs (aka Data) properly. (#1143)
* When encoding binary blobs (aka Data) for pretty-printing generate
text that is compatible with utf-8 which is used in python3, which means
escaping upper half of the code space. Without this attempt to make
printable representation of the valid otherwise binary data in python
could fail with something like this:

Traceback (most recent call last):
  File "./tools/lib/logreader.py", line 147, in <module>
    print(msg)
  File "capnp/lib/capnp.pyx", line 1092, in capnp.lib.capnp._DynamicStructReader.__str__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 118: invalid start byte

The structure in question is:

struct CanData {
  address @0 :UInt32;
  busTime @1 :UInt16;
  dat     @2 :Data;
  src     @3 :UInt8;
}

The data:

( logMonoTime = 166125304492147,
  sendcan = [
    ( address = 832,
      busTime = 0,
      dat = "\004\000\000$d\000\235\021",
      src = 0 ) ],
  valid = true )

Treat only DATA as non-UTF-8, the rest should be using previous algorithm.

* o Add some utf-8 text into encodeCEscape(chars) test case.

o Test encodeCEscape(bytes) as well with some non-utf8 bytes.